export const data = [
  { actividad: "Jugar a beisbol" },
  { actividad: "Ver peliculas" },
  { actividad: "Hacer ejercicio" },
  { actividad: "Leer un libro" },
  { actividad: "Jugar a videojuegos" },
  { actividad: "Estudiar" },
  { actividad: "Ir al cine" },
  { actividad: "Tomar una pausa" },
  { actividad: "Ver documentales" },
  { actividad: "Leer un articulo" },
  { actividad: "Comer" },
  { actividad: "Beber agua" },
  { actividad: "Ver series" },
  { actividad: "Leer noticias" },
  { actividad: "Dormir" },
  { actividad: "Trabajar" },
];
